name: Post Merge

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

permissions:
  contents: read

jobs:
  tests:
    uses: ./.github/workflows/ci.yml

  tag-release:
    needs:
      - tests
    permissions:
      contents: write
    uses: govuk-pay/pay-ci/.github/workflows/_create-alpha-release-tag.yml@c1bed255fa76164f86f2b0f0f20df26ea58ab1c6
